# Generated by Django 5.0.1 on 2024-02-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='cv_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='developer',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
